---
AllCops:
  DisplayCopNames:   true
  TargetRubyVersion: 2.6

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*'

Naming/FileName:
  Exclude:
    - lib/evil-client.rb

Naming/MethodParameterName:
  MinNameLength: 2

Naming/VariableNumber:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/Alias:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RescueModifier:
  Exclude:
    - '**/*_spec.rb'

Style/Semicolon:
  Exclude:
    - '**/*_spec.rb'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SingleLineMethods:
  Exclude:
    - '**/*_spec.rb'
